# -*- coding: utf-8 -*-
"""DigitRecognizer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UD4H78LO2m3tmTDx4-EN42bNL1mRbIIZ
"""

!ls

!tar -xvf train.tar.gz

!tar -xvf test.tar.gz

data = ImageDataBunch.from_folder('/content/trainingSet', valid_pct = 0.2).normalize()

learn = cnn_learner(data, models.resnet34, metrics=[accuracy])

data

learn.unfreeze()
learn.lr_find()
learn.recorder.plot()

learn.fit_one_cycle(2, max_lr=slice(1e-3,1e-2))

